"""
scene_builder.py
================
Converts a SceneDescription (from scene_bridge.py) into the layout JSON
format expected by MoLMoSpaces (molmospaces-main).

Layout JSON schema (from FloorPlan203_object_positions.json):
    {
        "scene_xml": "assets/scenes/...",
        "coordinate_frame": "mujoco_world",
        "human_runtime": {
            "enabled": true,
            "human_xml": "assets/humans/.../character.xml",
            "human_pos": [x, y, 0.0],
            "human_yaw_deg": float,
            ...
            "extra_humans": [...]
        },
        "objects": [...],
        "robot_runtime": { "robot_type": "navbot", "robot_base": [x,y,0] }
    }

Human XML assets available (relative to molmospaces-main/):
    assets/humans/standing_idle_multimat/character.xml
    assets/humans/sitting_2_multimat_matchedscale/character.xml
    assets/humans/remy_talking_multimat/character.xml
    assets/humans/rony_talking_multimat/character.xml
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

from .scene_bridge import SceneDescription, HumanInfo

# ---------------------------------------------------------------------------
# State → MJCF asset mapping
# Add more entries as new human models are added to assets/humans/
# ---------------------------------------------------------------------------

_STATE_TO_XML: dict[str, str] = {
    "idle":    "assets/humans/standing_idle_multimat/character.xml",
    "sitting": "assets/humans/sitting_2_multimat_matchedscale/character.xml",
    "talking": "assets/humans/remy_talking_multimat/character.xml",
    "walking": "assets/humans/standing_idle_multimat/character.xml",  # fallback
}

# Talking pairs get alternating models so they look different
_TALKING_MODELS = [
    "assets/humans/remy_talking_multimat/character.xml",
    "assets/humans/rony_talking_multimat/character.xml",
]

_DEFAULT_COLLIDER_STANDING = {"type": "capsule", "size": [0.2, 0.85, 0.55]}
_DEFAULT_COLLIDER_SITTING  = {"type": "capsule", "size": [0.28, 1.65, 0.0]}


def _human_xml_for_index(human: HumanInfo, human_idx: int, talking_count: list) -> str:
    """Pick MJCF XML for this human, cycling through talking models for pairs."""
    if human.state == "talking":
        idx = talking_count[0] % len(_TALKING_MODELS)
        talking_count[0] += 1
        return _TALKING_MODELS[idx]
    return _STATE_TO_XML.get(human.state, _STATE_TO_XML["idle"])


def _human_collider(state: str) -> dict:
    if state == "sitting":
        c = _DEFAULT_COLLIDER_SITTING
    else:
        c = _DEFAULT_COLLIDER_STANDING
    return {
        "human_collider_type": c["type"],
        "human_collider_size": c["size"],
    }


def scene_description_to_layout_json(
    scene: SceneDescription,
    scene_xml: str,
    robot_start: tuple[float, float, float] = (-1.4, 4.6, 0.0),
) -> dict:
    """
    Build a complete layout JSON dict from a SceneDescription.

    Parameters
    ----------
    scene :
        SceneDescription produced by scene_bridge.scene_graph_to_scene_description.
    scene_xml :
        Relative path to the MuJoCo scene XML (e.g. "assets/scenes/ithor/FloorPlan203_physics.xml").
    robot_start :
        Robot starting pose (x, y, yaw_deg).

    Returns
    -------
    dict ready to be written to a layout JSON file.
    """
    if not scene.humans:
        raise ValueError("SceneDescription has no humans — nothing to place.")

    talking_count = [0]   # mutable counter threaded through calls

    primary = scene.humans[0]
    primary_xml = _human_xml_for_index(primary, 0, talking_count)

    human_runtime: dict = {
        "enabled": True,
        "human_static": True,
        "human_xml": primary_xml,
        "human_pos": [primary.pos[0], primary.pos[1], 0.0],
        "human_yaw_deg": float(primary.yaw_deg),
        "human_roll_deg": 90.0,
        "human_pitch_deg": 0.0,
        "human_z_offset": 0.0,
        **_human_collider(primary.state),
        "extra_humans": [],
    }

    for h in scene.humans[1:]:
        xml = _human_xml_for_index(h, len(human_runtime["extra_humans"]) + 1, talking_count)
        entry: dict = {
            "enabled": True,
            "human_static": True,
            "human_xml": xml,
            "human_pos": [h.pos[0], h.pos[1], 0.0],
            "human_yaw_deg": float(h.yaw_deg),
            "human_roll_deg": 90.0,
            "human_pitch_deg": 0.0,
            "human_z_offset": 0.0,
            **_human_collider(h.state),
        }
        human_runtime["extra_humans"].append(entry)

    layout = {
        "scene_xml": scene_xml,
        "coordinate_frame": "mujoco_world",
        "notes": "Auto-generated by pipeline/scene_builder.py from HumanSSG output.",
        "human_runtime": human_runtime,
        "objects": [],
        "overrides": {},
        "robot_runtime": {
            "enabled": True,
            "robot_type": "navbot",
            "robot_base": [robot_start[0], robot_start[1], robot_start[2]],
            "robot_pos": [0.0, -0.15, 0.0],
        },
    }

    return layout


def patch_layout_json(
    existing_layout_path: str | Path,
    scene: SceneDescription,
    output_path: str | Path | None = None,
) -> dict:
    """
    Update only the human_runtime section of an existing layout JSON with
    positions/states from a new SceneDescription, preserving all other fields
    (scene_xml, objects, overrides, robot_runtime, ...).

    Parameters
    ----------
    existing_layout_path :
        Path to the base layout JSON (e.g. FloorPlan203_object_positions.json).
    scene :
        New SceneDescription from the latest 3DSG run.
    output_path :
        Where to write the patched JSON.  None = overwrite in-place.

    Returns
    -------
    The updated layout dict.
    """
    with open(existing_layout_path) as f:
        layout = json.load(f)

    talking_count = [0]

    if scene.humans:
        primary = scene.humans[0]
        primary_xml = _human_xml_for_index(primary, 0, talking_count)
        layout["human_runtime"].update({
            "enabled": True,
            "human_xml": primary_xml,
            "human_pos": [primary.pos[0], primary.pos[1], 0.0],
            "human_yaw_deg": float(primary.yaw_deg),
            **_human_collider(primary.state),
            "extra_humans": [],
        })
        for h in scene.humans[1:]:
            xml = _human_xml_for_index(h, len(layout["human_runtime"]["extra_humans"]) + 1, talking_count)
            layout["human_runtime"]["extra_humans"].append({
                "enabled": True,
                "human_static": True,
                "human_xml": xml,
                "human_pos": [h.pos[0], h.pos[1], 0.0],
                "human_yaw_deg": float(h.yaw_deg),
                "human_roll_deg": 90.0,
                "human_pitch_deg": 0.0,
                "human_z_offset": 0.0,
                **_human_collider(h.state),
            })
    else:
        layout["human_runtime"]["enabled"] = False

    dest = Path(output_path) if output_path else Path(existing_layout_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w") as f:
        json.dump(layout, f, indent=2)

    return layout


def save_layout_json(layout: dict, output_path: str | Path) -> None:
    """Write a layout dict to disk."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as f:
        json.dump(layout, f, indent=2)
